Models/Armazem.cs
using System.Collections.Generic;
using System;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace MVC_test.Models
{
    public class Armazem
    {
        
        public List<Produtos> Lista { get; set; }
        [Key] public DateTime Data { get; set; }

        public Armazem()
        {
            Lista = new List<Produtos>();
        }

        public Armazem(DateTime d) : this()
        {
            Data = d;
        }

        public double DiferencaDeValor(Armazem outro)
        {
            return (Lista.Sum(total => total.Preco) - outro.Lista.Sum(t => t.Preco));
        }

    }
}

Models/BancotesteContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MVC_test.Models
{
    public partial class BancotesteContext : DbContext
    {
 
        public BancotesteContext()
        {
        }

        public BancotesteContext(DbContextOptions<BancotesteContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseMySql("server=localhost;database=bancoteste;uid=Developer;password=123456789");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {}
    }
}

Models/ErrorViewModel.cs
using System;

namespace MVC_test.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Produtos.cs
namespace MVC_test.Models
{
    public class Produtos
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Tipos Tipo { get; set; }
        public double Preco { get; set; }

        public Produtos()
        {

        }

        public Produtos(int id, string n, Tipos t, double p)
        {
            Id = id;
            Nome = n;
            Tipo = t;
            Preco = p;
        }
    }
}

Models/Tipos.cs
namespace MVC_test.Models
{
    public enum Tipos
    {
        Comestível,
        Eletrônico,
        Móvel,
        Papelaria,
        Medicamento

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_test.Models;

namespace MVC_test.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_test.Models;
using MVC_test.Services;

namespace MVC_test.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly ProdutosService _ps;
         public ProdutosController(ProdutosService p)
        {
            _ps = p;
        }

        public async Task<IActionResult> Index()
        {
            var list = await _ps.FindAllAsync();
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Produtos obj)
        {
            await _ps.InsertAsync(obj);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? a)
        {
            if(a == null)
            {
                return NotFound();
            }

            var obj = await _ps.FindByIdAsync(a.Value);
            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [
            HttpPost
        ]
        [ValidateAntiForgeryTokenAttribute]
        public async Task<IActionResult> Delete(int Id)
        {
            await _ps.RemoveAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Produtos/Create.cshtml
@model MVC_test.Models.Produtos

@{
    ViewData["Title"] = "Create";
}

<h2>Novo Produto</h2>

<h4>Preencha o formulário</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                @Html.DropDownList("Tipo", 
                Html.GetEnumSelectList<Tipos>(),
                "Escolha um Tipo",new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

Views/Produtos/Delete.cshtml
@model MVC_test.Models.Produtos

@{
    ViewData["Title"] = "Delete";
}

<h2>Deletar</h2>

<h3>Você tem certeza que deseja deletar o produto?</h3>

<div>
    <h4>Produto</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Deletar" class="btn btn-danger" />
        <a asp-action="Index">Voltar para a lista</a>
    </form>
</div>

Views/Produtos/Index.cshtml
@model IEnumerable<MVC_test.Models.Produtos>
@{
    ViewData["Title"] = "Products";
}

<div class="text-center">
    <h1 class="display-4">Página de Produtos</h1>
    <p>Mostrando os produtos de nosso DataBase.</p>

    <p>
        <a asp-action="Create" class="btn btn-dark">Novo_Produto</a>
        Teste
    </p>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Preco)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelp => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelp => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelp => item.Tipo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelp => item.Preco)
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-a="@item.Id">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_test</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrapnew.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MVC_test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>